FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/Host/ModularCommerce.API/ModularCommerce.API.csproj", "src/Host/ModularCommerce.API/"]
RUN dotnet restore "./src/Host/ModularCommerce.API/ModularCommerce.API.csproj"
COPY . .
WORKDIR "/src/src/Host/ModularCommerce.API"
RUN dotnet build "./ModularCommerce.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./ModularCommerce.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ModularCommerce.API.dll"]