<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Apis\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\ModularCommerce.Modules.Catalog\ModularCommerce.Modules.Catalog.csproj" />
    <ProjectReference Include="..\..\Modules\ModularCommerce.Modules.Orders\ModularCommerce.Modules.Orders.csproj" />
  </ItemGroup>

</Project>
